version: "3.2"

services:
  postgres-dev:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
    ports:
      - 54320:5432
    networks:
      - api_dev

networks:
  api_dev:
    driver: bridge
