version: "3.7"

services:
  postgres-test:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 54321:5432
    networks:
      - api_test

networks:
  api_test:
    driver: bridge
