global:
  scrape_interval: 5s
  evaluation_interval: 5s

  external_labels:
    monitor: "api"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api"
    static_configs:
      - targets: ["localhost:4000"]

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - localhost:8080
